### ISSUE TITLE
feature: support custom package providers

### ISSUE THREAD

**Issue by merusso** [ekristen/distillery#250]
I want to install a package that doesn't provide a GitHub release but is available through a pattern-based URL including the package version.

For example, the AWS CLI is available via pattern `https://awscli.amazonaws.com/AWSCLIV2-{version}.pkg` ([docs](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html))

Ideally I could configure a custom provider that includes the URL pattern, and I could reference this provider to install new versions of the package.

Example config:
```
custom_providers:
  - name: aws
    url_pattern: https://awscli.amazonaws.com/AWSCLIV2-{version}.pkg
```

Example usage:
```
$ dist install aws/aws@2.27.12
```

**Comment by merusso** [comment]
Great tool, by the way! I've been looking for something that does exactly what this is designed to do. I haven't been happy with how most tools (Homebrew for example) handle versioning and rollbacks.

For some tools where I need more precise version management, I've been manually managing package versions using symlinks, the same way this tool works.

**Comment by ekristen** [comment]
@merusso thanks! I love this idea. I started on something like this but then got distracted so never finished it. I'll see if I can come back around to it. I don't think it would be super hard, the only caveat is when you get into architectures a bit, especially around arm, there can be multiple ways that's expressed.

**Comment by merusso** [comment]
I thought a little about that. For example, let's look at `kubectl`.

For version 1.31.8, the client download URLs are [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md#downloads-for-v1318).
The pattern appears to be: `https://dl.k8s.io/v{version}/kubernetes-client-{os}-{arch}.tar.gz`
For Mac with Apple Silicon, the download URL is: https://dl.k8s.io/v1.31.8/kubernetes-client-darwin-arm64.tar.gz

The _simplest_ option would be to just bake the OS and architecture into the URL pattern. This config would work for an individual user but wouldn't be cross-platform. For example, I could set the pattern to `https://dl.k8s.io/v{version}/kubernetes-client-darwin-arm64.tar.gz` and it would work for a Mac with Apple Silicon. This doesn't seem too bad for a first pass.

If you wanted a config that worked for multiple platforms/architectures, you might need some mapping in the config to map the OS/ARCH detected by Distillery to the strings used by the URL pattern.

```
custom_providers:
  - name: aws
    url_pattern: https://some-custom-package-registry/my-package-{os}-{arch}-{version}.pkg
    # Maps detected GOOS value to specific string
    os_mapping:
      darwin: mac
      windows: win
    # Maps detected GOARCH value to specific string
    arch_mapping:
      arm64: arm
      amd64: x64
```
